Implementation of transformer model
chainer/models pull request #37
Opened 2019-08-15 11:37 UTC by Bartzi

This PR adds an example implementation of the Transformer, as introduced in the Paper [Attention is all you need](http://papers.nips.cc/paper/7181-attention-is-all-you-need).

Let me know, if there is anything I should change or add.

2019-08-22 23:19 UTC, soskek requested changes
Thank you for your PR! It seems good at a glance while it deals with a toy copy task only.

2019-08-22 23:19 UTC, soskek commented on transformer/updater/copy_transformer_updater.py
> +        with self.device.device:
This part may work on GPU only.
If this script runs on CPU, it causes an error.
```
AttributeError: 'CpuDevice' object has no attribute 'device'
```

Could you solve this kind of errors? Or, recommend users to use GPU. Currently, the default argparse selects CPU (-1).

2019-09-02 08:45 UTC, Bartzi commented
I changed all occurences of this problem.
Please have a look again =)

2019-09-02 11:00 UTC, soskek commented
Thanks!

In a quick check, I found this doesn't seem to work when I set args.gpu != 0 in machines with one or more GPUs. I guessed this may be derived from usages of `with cuda.get_device(self.device):` and/or `with cuda.Device(self.device):`.

### args.gpu = -1
i.e. using CPU while the machine has GPU

```
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py", line 161, in __call__
    result = self.evaluate()
  File "/home/sosk/models/transformer/evaluation/copy_transformer_eval_function.py", line 55, in evaluate
    eval_func(data=data, label=data)
  File "/home/sosk/models/transformer/evaluation/copy_transformer_eval_function.py", line 16, in __call__
    with cuda.Device(self.device):
  File "cupy/cuda/device.pyx", line 126, in cupy.cuda.device.Device.__enter__
  File "cupy/cuda/device.pyx", line 141, in cupy.cuda.device.Device.use
  File "cupy/cuda/runtime.pyx", line 193, in cupy.cuda.runtime.setDevice
  File "cupy/cuda/runtime.pyx", line 145, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal
```

### args.gpu = 2

i.e. using GPU whose device id is 2 when the machine may have more than 2 GPUs

```
Traceback (most recent call last):
  File "train_copy.py", line 56, in <module>
    main(args)
  File "train_copy.py", line 42, in main
    trainer.run()
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/home/sosk/models/transformer/updater/copy_transformer_updater.py", line 12, in update_core
    self.update_net()
  File "/home/sosk/models/transformer/updater/copy_transformer_updater.py", line 22, in update_net
    predictions = net(batch['data'], batch['label'][:, :-1])
  File "/home/sosk/models/transformer/chains/copy_transformer.py", line 42, in __call__
    result = self.model(x, t, None, self.mask)
  File "/home/sosk/models/transformer/transformer/encoder_decoder.py", line 30, in __call__
    tgt_mask
  File "/home/sosk/models/transformer/transformer/encoder_decoder.py", line 37, in decode
    return self.decoder(self.tgt_embeddings(tgt), memory, src_mask, tgt_mask)
  File "/home/sosk/models/transformer/transformer/decoder.py", line 30, in __call__
    x = layer(x, memory, src_mask, tgt_mask)
...
...
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/where.py", line 90, in where
    z, = Where(condition).apply((x, y))
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py", line 321, in apply
    outputs = self.forward(in_data)
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/where.py", line 36, in forward
    return xp.where(condition, x, y),
  File "/home/sosk/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/cupy/sorting/search.py", line 136, in where
    return _where_ufunc(condition.astype('?'), x, y)
  File "cupy/core/core.pyx", line 318, in cupy.core.core.ndarray.astype
  File "cupy/core/core.pyx", line 389, in cupy.core.core.ndarray.astype
  File "cupy/core/_kernel.pyx", line 811, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 94, in cupy.core._kernel._preprocess_args
ValueError: Array device must be same as the current device: array device = 0 while current = 2
```



And, if you're involved with PRs, force-push seems not a good choice, because comparing the changes can be difficult (while we can compare with [a github feature](https://github.com/chainer/models/compare/3b58974cddbe282294a59af2598eb5c51d982db7..e4eef8fbda5834dee5c7ae7e14dff92b32fdd6e9)).

2019-09-04 13:50 UTC, Bartzi commented
Thanks for reviewing again.
You are totally right, the force push was not the smartest idea :sweat_smile:.
I had a look at the GPU stuff again and I think I finally found a working solution, although I'm not really happy with it. The API seems to be totally messed up in the newer versions of Chainer. Am I using them wrong? There should be a nicer way to write CPU/GPU agnostic code, shouldn't it?

2019-09-27 14:21 UTC, soskek commented
Sorry for late reply. I missed it.

Did you see APIs used in any Chainer example code?
https://github.com/chainer/chainer/blob/v6.0.0/examples/mnist/train_mnist.py#L56-L69
It easily selects a device as default in the script. This API seems one of the best ways for simplifying your code.

```
device = chainer.get_device(args.device)
...
model.to_device(device)
device.use()
```

2019-10-10 13:58 UTC, Bartzi commented
I did not see this. Seems to be the new way of handling devices. Thanks for the heads up! I will change the implementation as soon as I have time!

2020-01-08 15:16 UTC, Bartzi commented
Sorry that it took me so long. I've updated the CPU/GPU usage code and adapted it to the new style, which is used since Chainer v6. Please have a look again.

2020-01-09 01:07 UTC, soskek requested changes
Thank you! It works well.
Only one comment.

2020-01-09 01:07 UTC, soskek commented on transformer/README.md
> +a GPU for training, you can specify the GPU with `-g`. For further options
Now, it is `-d` rather than `-g`.

2020-01-09 08:09 UTC, Bartzi commented
Thanks for having a look again and spotting this mistake. I changed the README accordingly.

2020-01-09 12:24 UTC, soskek approved these changes
Thank you for the great work! Merged!

2020-01-09 12:24 UTC, merged